### ISSUE TITLE
Hey nice work man

### ISSUE THREAD

**Issue by asafravid** [SuckDuck/WatchDrop#1]
Could you add a feature to enumerate the copied files?
Consider a case where some error log file appears, so you copy it somewhere right? But then if another one appears after this one was deleted, and that new file is with the same name, that original copied file would be overridden
So soliton: add an inumeration 1,2,3,... to its name

Thanks!
Maybe I'll try to implement it myself and create a pull request, when/if I got time

Thanks

**Comment by SuckDuck** [comment]
Hey thank you so much!!.
But i didn't understand, if a log file appears then a save dialog will pop up asking you not only where to place it but what name give it, so the original log will be overwritten only if you save the new one in the same path and with the same name, and even then the save dialog will ask you twice if you really want to overwrite it

**Comment by asafravid** [comment]
Hey thanks for clarifying 
Is there a possibility then to add a checkmark which states that if it is checked marked then auto file name suffix will be added when similar (same name) files appear? Avoiding the dialog in next times?
I can elaborate if required

**Comment by SuckDuck** [comment]
Oh i think i got it now.
That seems doable!, or maybe something else for the same purpose,
if you want to collaborate i will be very pleasant, but i have to warn you that the code is a little messy right now, i will probably refactor it soon
